services:
  postgres:
    image: postgres:16
    container_name: petshop-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petshopdb
    ports:
      - "5432:5432"
    volumes:
      - ./init-db-test.sh:/docker-entrypoint-initdb.d/init-db-test.sh